// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa7xBWhscT48Lz4asJpZWuTQezKaftirU',
    appId: '1:1087081553297:web:987510f4f8235480000e30',
    messagingSenderId: '1087081553297',
    projectId: 'healhify-8755a',
    authDomain: 'healhify-8755a.firebaseapp.com',
    storageBucket: 'healhify-8755a.appspot.com',
    measurementId: 'G-FCLCQBCXEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBURSjNO3kh3nn8UokpbWzC_YQxwtJvYmI',
    appId: '1:1087081553297:android:f8b2564f58787bdb000e30',
    messagingSenderId: '1087081553297',
    projectId: 'healhify-8755a',
    storageBucket: 'healhify-8755a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl5IpvI7gpJvmp3TaZjin88eRm9twyQUA',
    appId: '1:1087081553297:ios:f772fed1846f95c6000e30',
    messagingSenderId: '1087081553297',
    projectId: 'healhify-8755a',
    storageBucket: 'healhify-8755a.appspot.com',
    iosBundleId: 'com.example.healhify',
  );
}
